require('plugins._packer')
require('plugins._formatter')
require('plugins._telescope')
require('plugins._treesitter')
require('plugins._bufferline')
require('plugins._nvim-comment')
require('plugins._nvim-cmp')
require('plugins.git')
